import React from 'react';
import { FileText, Scale, AlertCircle, CheckCircle, HelpCircle } from 'lucide-react';

const Section = ({ title, children }) => (
  <div className="mb-10">
    <h2 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
      <div className="w-1.5 h-1.5 rounded-full bg-cyan-500" />
      {title}
    </h2>
    <div className="text-slate-400 leading-relaxed text-sm space-y-4 pl-4 border-l border-white/5">
      {children}
    </div>
  </div>
);

const Terms = () => {
  return (
    <div className="min-h-screen pt-24 pb-20 bg-[#020617] relative overflow-hidden">
      {/* Background Effects */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#0f172a_1px,transparent_1px),linear-gradient(to_bottom,#0f172a_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] opacity-20 pointer-events-none" />
      <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-purple-500/5 rounded-full blur-[120px] pointer-events-none" />
      
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Header */}
        <div className="text-center mb-20">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-xs font-mono mb-6">
            <Scale className="w-3 h-3" />
            LEGAL AGREEMENT
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-6 tracking-tight font-display">
            Terms of <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-500">Service</span>
          </h1>
          <p className="text-slate-400 max-w-2xl mx-auto">
            Please read these terms carefully before using the CuraVyom platform. By accessing our services, you agree to be bound by these terms.
          </p>
        </div>

        {/* Content */}
        <div className="bg-slate-950/50 border border-white/10 rounded-2xl p-8 md:p-12 backdrop-blur-xl">
          
          <Section title="1. Acceptance of Terms">
            <p>
              By accessing and using the CuraVyom AI platform ("Service"), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services.
            </p>
          </Section>

          <Section title="2. Use License">
            <p>
              Permission is granted to temporarily access the materials (information or software) on CuraVyom's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
            </p>
            <ul className="list-disc pl-5 space-y-2 marker:text-purple-500">
              <li>modify or copy the materials;</li>
              <li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
              <li>attempt to decompile or reverse engineer any software contained on CuraVyom's website;</li>
            </ul>
          </Section>

          <Section title="3. AI Disclaimer">
            <div className="p-4 rounded-lg bg-yellow-500/10 border border-yellow-500/20 flex gap-3 items-start">
              <AlertCircle className="w-5 h-5 text-yellow-500 shrink-0 mt-0.5" />
              <p className="text-yellow-200/80 text-xs leading-relaxed">
                The insights provided by CuraVyom are generated by Artificial Intelligence and are for research assistance purposes only. They do not constitute medical advice or final clinical determinations. All AI-generated findings should be verified by qualified professionals.
              </p>
            </div>
          </Section>

          <Section title="4. Intellectual Property">
            <p>
              The Service and its original content, features, and functionality are and will remain the exclusive property of CuraVyom Pharmaceuticals and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.
            </p>
          </Section>

          <Section title="5. Termination">
            <p>
              We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>
          </Section>

          <div className="mt-12 flex items-center justify-between pt-8 border-t border-white/10">
            <div className="flex items-center gap-2 text-slate-500 text-sm">
              <CheckCircle className="w-4 h-4 text-green-500" />
              <span>Effective Date: November 30, 2025</span>
            </div>
            <button className="text-sm text-purple-400 hover:text-purple-300 flex items-center gap-2 transition-colors">
              <HelpCircle className="w-4 h-4" />
              Have questions?
            </button>
          </div>

        </div>
      </div>
    </div>
  );
};

export default Terms;
